version: "3"
services:
  frontend:
    image: doyts/demoloadbalancer_frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    deploy:
      replicas: 4
    networks:
      - loadbalancing

  nginx:
    image: doyts/demoloadbalancer_loadbalancer
    build:
      context: .
      dockerfile: loadbalancer.Dockerfile
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - frontend

networks:
  loadbalancing:
